all:calculate_square
	  
calculate_square: count_args
	gcc calculate_square.c -o calculate_square.out

count_args: strlen
	gcc count_args.c -o count_args.out

strlen: main
	gcc strlen.c  -o strlen.out

main: 
	gcc main.c  -o main.out
